### ISSUE TITLE
Dependency on Material3

### ISSUE THREAD

**Issue by ThibautPerrinDiabeloop** [NordicSemiconductor/Kotlin-BLE-Library#119]
When using this library (`no.nordicsemi.android.kotlin.ble:client`), we get a dependency on `androidx.compose.material3`
When we already use material3 with a different version, versions are conflicting...

Material 3 seems to be used only by `app_client` module. Why this dependency is embedded in `no.nordicsemi.android.kotlin.ble:client` ?

**Comment by philips77** [comment]
Good catch. Let me check it.

**Comment by philips77** [comment]
OK. I did some investigation. The `:client` and some other modules depend on `libs.nordic.common.core`, which depends on `androidxcompose.material3`. But the only classes used from that module are `DataByteArray`.
I will remove the dependency to `common.core` and will solve the issue some other way.

So what looks like minor dependency issue will bring breaking changes in the API, moving classes between modules and refactoring. I will keep you posted.

**Comment by philips77** [comment]
As far as I remember we needed the `ModalBottomSheet` and swipe to dismiss. Now, with 1.2.0 being final I'm changing the dependencies and removing unnecessary dependencies. Should be ready in couple of days, but with breaking changes.
I'm also polishing the API of the library (class names) whenever I find inconsistency.

I'd like also to remove `DataByteArray` (see [here](https://github.com/NordicPlayground/Android-Common-Libraries/pull/85)) and migrate to `ByteArray`. If you need such class for array wrapper (to avoid `equals()` and `hashCode()` this can be added in the apps, not library. Integer extraction will be done using extensions for `ByteArray` (see [here](https://github.com/NordicPlayground/Android-Common-Libraries/pull/83)).
