### ISSUE TITLE
Missing and outdated documentation

### ISSUE THREAD

**Issue by piefel** [NordicSemiconductor/Kotlin-BLE-Library#139]
I was pointed to this library over from the classic [Android-BLE-Library](https://github.com/NordicSemiconductor/Android-BLE-Library/) and was at a loss how to start. Is there no documentation, or am I just unable to find it? The README is quite short, and it is outdated.

To be a bit more concrete:
 - Scanner: What’s the aggregrator for, how to actually use the found devices when we need a bit more than MAC addresses.
 - Client: You cannot `connect()` directly on the device (anymore?), and how do you handle connection changes etc.

**Comment by philips77** [comment]
I am rewriting the library at the moment, with the native client coming in few weeks. It won't be compatible with the current version. Until then, I recommend using the old Java-based library, despite what it says.

In the new one I hope to have more self-readable API and better doc as well.
I'll be pushing my code when only it gets usable so you can track it.

**Comment by abrown-sram** [comment]
How is the new library coming?

**Comment by philips77** [comment]
I aim to have the client ready in June, but at the moment I'm busy with another project so can't promise anything.

**Comment by philips77** [comment]
See #152.
