### ISSUE TITLE
How to set scan filter?

### ISSUE THREAD

**Issue by thedevleon** [NordicSemiconductor/Kotlin-BLE-Library#15]
Is there any way to set a scanning filter? [As far as I can see, it's set to null by default.](https://github.com/NordicSemiconductor/Kotlin-BLE-Library/blob/a59f4ecc2d179c062fd21c537b9617950bb4d56c/scanner/src/main/java/no/nordicsemi/android/kotlin/ble/scanner/BleScanner.kt#L112)

Is there a different way to filter the results?

**Comment by sylwester-zielinski** [comment]
It has been added in version 1.0.6. Feel free to reopen if there is something missing.
