### ISSUE TITLE
BleScanner  crash when created in airplane mode caused by nullable BluetoothAdapter#getBluetoothLeScanner()

### ISSUE THREAD

**Issue by m-ivanov** [NordicSemiconductor/Kotlin-BLE-Library#163]
Initializing  while in airplane mode  cause `NullPointerException: getBluetoothLeScanner(...) must not be null`

Android BluetoothAdapter#getBluetoothLeScanner return null in case BLE is off

```
class BleScanner(
    context: Context,
) {
    // ...
    init {
        // ...
        bluetoothLeScanner = bluetoothAdapter.bluetoothLeScanner
    }

```

**Comment by philips77** [comment]
Hi, please try the new version on _version/2.0_ branch.
