### ISSUE TITLE
Just found out about this. Can I try this out?

### ISSUE THREAD

**Issue by shwetankshrey** [NordicSemiconductor/Kotlin-BLE-Library#2]
I had been working on the BLE communication layer in my Android app and was checking out the Nordic Android BLE library. I would like to test out this library for my use cases as well. Is this library ready to be used?

**Comment by philips77** [comment]
Hello,
We are still polishing it and the API is not stable, but you may try, sure. Early feedback is much appreciated.
@sylwester-zielinski is also migrating nRF Toolbox to use this library: https://github.com/NordicSemiconductor/Android-nRF-Toolbox/commits/develop if you need an example.

**Comment by sylwester-zielinski** [comment]
Yes, the library is available.
