### ISSUE TITLE
CGM Sample

### ISSUE THREAD

**Issue by paratoner** [NordicSemiconductor/Kotlin-BLE-Library#28]
Could you please add CGM sample for ble measurement sensor device.

**Comment by sylwester-zielinski** [comment]
Continuous Glucose Monitor example is available in [nRF Toolbox app](https://play.google.com/store/apps/details?id=no.nordicsemi.android.nrftoolbox). The code with GATT configuration is available [here](https://github.com/NordicSemiconductor/Android-nRF-Toolbox/blob/18ad3d97bb77393fcf5e48d1baec1e7f71bb185c/profile_cgms/src/main/java/no/nordicsemi/android/cgms/repository/CGMService.kt#L135).

**Comment by paratoner** [comment]
Great! thank you very much.
