### ISSUE TITLE
ServerBleGattCharacteristic does not wait for a BluetoothGattServerCallback.onNotificationSent

### ISSUE THREAD

**Issue by mottljan** [NordicSemiconductor/Kotlin-BLE-Library#29]
Hello, first of all thank you very much for this awesome library! I have been using it for a few weeks for both client and server implementation and found a few issues/bugs I would like to report.

I will start with IMHO the most critical one, which is not waiting for `BluetoothGattServerCallback.onNotificationSent` when you call `ServerBleGattCharacteristic.setValue`. For some reason `setValue` is not `suspend` as other BLE actions you can make which is problematic for these reasons:

- I can't get a result of calling `setValue` on a characteristic that is notifiable and sends a notification to a client, so I can't process potential errors
- In my case I need to notify a client with quite a big message that needs to be split to several smaller chunks based on the available MTU and I need to wait for `BluetoothGattServerCallback.onNotificationSent` after sending a first chunk to be able to known when I can continue with another chunk etc.

I think that `setValue` should be `suspend` as other BLE actions in this library and should wait for `onNotificationSent` and resume either with error or success, so we can both process errors and reliably send more chunks of a message. I can actually see in the code that `BluetoothGattServerCallback.onNotificationSent` is propagated all the way to the characteristic but then it is handled by a private empty `onNotificationSent` method, so maybe someone just forgot to finish this implementation.

If someone had a same issue, currently I work around this by accessing a private `server` property of `ServerBleGatt` using a reflection and observing its `event` stream to get an event emission about a processed notification. Really bad and hacky but does a job for now.

**Comment by sylwester-zielinski** [comment]
That's a good point, but not every characteristic has `NOTIFY` or `INDICATE` property. I added `setValueAndNotifyClient` function which suspends for `onNotificationSent` callback. From now on `setValue` only sets local value (available later for read operation) without notifying client.
