### ISSUE TITLE
Something broke 1.0.6 => 1.0.8 notifying subscriptions as server

### ISSUE THREAD

**Issue by reactormonk** [NordicSemiconductor/Kotlin-BLE-Library#62]
I have a server where `setValue` is being called on a regular basis, but when upgrading 1.0.6 to 1.0.8, only first value gets propagated, the client doesn't receive updates anymore.

**Comment by sylwester-zielinski** [comment]
New function has been added `setValueAndNotifyClient` which sets value, notify listeners and waits for a proper callback to finish. `setValue` is now used only for setting value for READ operations. I will change the name of this to maybe `setLocalValue` to avoid confusion in the future.

**Comment by reactormonk** [comment]
Or go for `setValueForRead`, and `setValueAndNotifyClient`?

**Comment by philips77** [comment]
Or `setValue` and `setValueLocally`? I understand the first one sets also for read and notifies all subscribed clients, the other one just sets the value.

Regarding versioning, it should all be 0.x-alpha, i think. Lots of things may still change. Please forgive us :)
