### ISSUE TITLE
Plans for a user documentation?

### ISSUE THREAD

**Issue by TSS-22** [NordicSemiconductor/Kotlin-BLE-Library#98]
Hello,
Is there any plans for user documentation of the library, and examples using this library instead of the android-ble-library as present?

Thanks for your time and efforts.

**Comment by philips77** [comment]
Hello,
Sure, there will be documentation. We need to stabilize the API first. For now you may check out [nRF Toolbox](https://github.com/NordicSemiconductor/Android-nRF-Toolbox) as an example.

**Comment by TSS-22** [comment]
Perfect, thanks a lot!
